AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    Noritex SAM

    Noritex SAM Project

Globals:
    Function:
        Timeout: 900
Parameters:
    Alias:
        Type: String
        Default: stage
        AllowedValues:
            - prod
            - stage
            - m1.large
        Description: Enter prod, stage
Resources:
    libs:
            Type: AWS::Serverless::LayerVersion
            Properties:
                ContentUri: ../libs-layer
                CompatibleRuntimes:
                    - python3.9
                    - python3.8
                    - python3.7
                    - python3.6
    GetFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../productGet/
            Handler: get.lambda_handler
            Runtime: python3.8
            Environment:
                Variables:
                    MONGO_SRV: "mongodb+srv://esteban:esteban@devtests.tydv7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority" 
                    MONGO_DATABASE: "noritex"
                    CDN: "https://www.noritex.com"
                    S3BUCKET: "estebanber2"
            Events:
                ProductGet:
                    Type: Api 
                    Properties:
                        Path: /product
                        Method: get
    PostFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../productPut/
            Handler: put.lambda_handler
            Runtime: python3.8
            Layers:
              #- !Sub arn:aws:lambda:us-east-2:${AWS::AccountId}:layer:pillow:1
               - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-Pillow:1
            Environment:
                Variables:
                    MONGO_SRV: "mongodb+srv://esteban:esteban@devtests.tydv7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority" 
                    MONGO_DATABASE: "noritex"
                    CDN: "https://www.noritex.com"
                    S3BUCKET: "estebanber2"
                    RECOMBEE_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:recombee
                    ELASTICSEARCH_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:elasticSearch
            Events:
                ProductPost:
                    Type: Api 
                    Properties:
                        Path: /product
                        Method: post
            Policies:
                - Statement:
                      - Sid: LambdaescribeParametersPolicy
                        Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: "*"
                - Statement:
                      - Sid: S3ObjectPut
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:PutObject
                            - s3:PutObjectAcl
                        Resource: arn:aws:s3:::estebanber2/*
    PutFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../productPut/
            Handler: put.lambda_handler
            Runtime: python3.8
            FunctionName: putFunction
            Layers:
              #- !Sub arn:aws:lambda:us-east-2:${AWS::AccountId}:layer:pillow:1
                - !Ref libs
                - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-Pillow:1
            Environment:
                Variables:
                    MONGO_SRV: "mongodb+srv://esteban:esteban@devtests.tydv7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority" 
                    MONGO_DATABASE: "noritex"
                    CDN: "https://www.noritex.com"
                    S3BUCKET: "estebanber2"
                    RECOMBEE_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:recombee
                    ELASTICSEARCH_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:elasticSearch
            Events:
                ProductPut:
                    Type: Api
                    Properties:
                        Path: /product
                        Method: put
            Policies:
                - Statement:
                      - Sid: LambdaescribeParametersPolicy
                        Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: "*"
                - Statement:
                      - Sid: S3ObjectPut
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:PutObject
                            - s3:PutObjectAcl
                        Resource: arn:aws:s3:::estebanber2/*
    DeleteFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../productDelete/
            Handler: delete.lambda_handler
            Runtime: python3.8
            Environment:
                Variables:
                    MONGO_SRV: "mongodb+srv://esteban:esteban@devtests.tydv7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority" 
                    MONGO_DATABASE: "noritex"
                    CDN: "https://www.noritex.com"
                    S3BUCKET: "estebanber2"
                    RECOMBEE_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:recombee
                    ELASTICSEARCH_LAMBDA: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:elasticSearch
            Events:
                ProductDelete:
                    Type: Api
                    Properties:
                        Path: /product
                        Method: delete
            Policies:
                - Statement:
                      - Sid: S3ObjectPut
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:PutObject
                            - s3:PutObjectAcl
                        Resource: arn:aws:s3:::ntx-media-public/*
                - Statement:
                      - Sid: LambdaescribeParametersPolicy
                        Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: "*"
    ElasticSearchFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../elasticsearch/
            Handler: app.lambda_handler
            Runtime: python3.8
            FunctionName: elasticSearch
            Environment:
                Variables:
                    ELASTICS_ENDPOINT: "http://172.19.0.2:9200"
                    ELASTICS_PRIVATE_KEY: "ELASTICS_PRIVATE_KEY"
                    ELASTICS_ENGINE: "ELASTICS_ENGINE"
    RecombeeFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../recombee/
            Handler: app.lambda_handler
            Runtime: python3.8
            FunctionName: recombee
            Environment:
                Variables:
                    RB_APIID: "nyx-prod"
                    RB_PRIVTOK: "hYyCYWngUZ4MjFrttPyxTI1M3r7TN2BpdXa4jMdeF65zgNVadEw5dvYlsbsEEOGb"
Outputs:
    ProductApi:
        Description: "API Gateway endpoint URL for Prod stage for product functions"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/"
    GetFunction:
        Description: "Get product Lambda Function ARN"
        Value: !GetAtt GetFunction.Arn
    PostFunction:
        Description: "Post product Lambda Function ARN"
        Value: !GetAtt PostFunction.Arn
    PutFunction:
        Description: "Put product Lambda Function ARN"
        Value: !GetAtt PutFunction.Arn
    DeleteFunction:
        Description: "Delete product Lambda Function ARN"
        Value: !GetAtt DeleteFunction.Arn
    ElasticSearchFunction:
        Description: "ElasticSearchFunction Lambda Function ARN"
        Value: !GetAtt ElasticSearchFunction.Arn
    RecombeeFunction:
        Description: "Recombee Lambda Function ARN"
        Value: !GetAtt RecombeeFunction.Arn
