AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    Noritex SAM

    Noritex SAM Project

Globals:
    Function:
        Timeout: 900
Parameters:
    Alias:
        Type: String
        Default: stage
        AllowedValues:
            - prod
            - stage
            - m1.large
        Description: Enter prod, stage

Resources:
    ClaimsFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: ../claims/
            Handler: app.lambda_handler
            Runtime: python3.8
            Environment:
                Variables:
                    MONGO_SRV: "mongodb+srv://esteban:esteban@devtests.tydv7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority" 
                    MONGO_DATABASE: "noritex"
                    KEY_COLLECTION: "products"
                    AWS_OUTPUT_LAMBDA: ecommerce-api-ClaimsFunction-js0EV2ipKzjp
                    DEFAULT_LOGO_IMAGE: "https://cdn.worldvectorlogo.com/logos/free-logo.svg" 
                    BASES3URL: "https://www.noritex.com"
                    S3BUCKET: "estebanber2"
            Events:
                claimsPost:
                    Type: Api 
                    Properties:
                        Path: /claims
                        Method: post
            Policies:
                - Statement:
                      - Sid: LambdaSendEmail
                        Effect: Allow
                        Action:
                            - ses:SendEmail
                            - ses:SendTemplatedEmail
                            - ses:SendRawEmail
                            - ses:SendBulkTemplatedEmail
                        Resource: "*"
                - Statement:
                      - Sid: LambdaescribeParametersPolicy
                        Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: "*"
                - Statement:
                      - Sid: S3ObjectPut
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:PutObject
                            - s3:PutObjectAcl
                        Resource: arn:aws:s3:::estebanber2/*
Outputs:
    ClaimsFunction:
        Description: "Send claims mails"
        Value: !GetAtt ClaimsFunction.Arn
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/claims/"
